#!/usr/bin/env python

from __future__ import absolute_import, division, print_function
import argparse
from limited_area.limited_area import LimitedArea

if __name__ == "__main__":
    DEBUG = 0

    kwargs = { 'DEBUG' : DEBUG , 'region.type': 'circle', 'region.name': 'hello',
            'region.in_point': [51., -5.0], 'region.radius': 200*1000}

    print(kwargs)

    regional_area = LimitedArea('global.grid.nc',
                                None,
                                format='NETCDF3_64BIT_OFFSET',
                                **kwargs)

    regional_area.gen_region(**kwargs)


    if DEBUG > 0:
        print("DEBUG: Limited Area Creation Finished")



