#!/usr/bin/env python

from __future__ import absolute_import, division, print_function
from limited_area.limited_area import LimitedArea
import os

if __name__ == "__main__":
    DEBUG = 0

    oregion = 'tmp/region.nc'
    ograph = 'tmp/region.graph.info'

    kwargs = {'DEBUG': DEBUG,
              'region.type': 'circle',
              'region.in_point': [51., -5.0],
              'region.radius': 200*1000}

    print(kwargs)

    regional_area = LimitedArea('global.grid.nc',
                                None,
                                format='NETCDF3_64BIT_OFFSET',
                                **kwargs)

    region_fname, graph_fname = regional_area.gen_region(**kwargs)

    if DEBUG > 0:
        print("DEBUG: Limited Area Creation Finished")

    if oregion is not None:
        pathregion = os.path.dirname(oregion)
        os.system('mkdir -p ' + pathregion)
        os.system('mv ' + region_fname + ' ' + oregion)
        print('Region available in ' + oregion)
        if ograph is None:
            ograph = oregion.replace('.nc', '') + '.graph.info'
        pathgraph = os.path.dirname(ograph)
        os.system('mkdir -p ' + pathgraph)
        os.system('mv ' + graph_fname + ' ' + ograph)
        print('Graph.info available in ' + ograph)
    else:
        print('Region available in ' + region_fname)
        print('Graph.info available in ' + graph_fname)

